version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: docker.io/mongo:6.0
    container_name: advisor-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=advisor
    volumes:
      - mongodb_data:/data/db

  # Backend service (serves API and static frontend)
  advisor:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: advisor
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=advisor
      - FRONTEND_ADDRESSES=http://localhost:8000,http://0.0.0.0:8000
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"

volumes:
  mongodb_data:
